image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install --upgrade pip
      pip install -r requirements.txt
      # use the new upgrade command in Airflow 3
      airflow db upgrade
      airflow connections create-default-connections
  - command: |
      pytest --maxfail=1 --disable-warnings -q

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
