name: "✅ Grade Brick E4"

on:
push:
branches: [ main ]
pull\_request:
branches: [ main ]
workflow\_dispatch:

jobs:
test:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: 3.11

  - name: Install system packages
    run: |
      sudo apt-get update
      sudo apt-get install -y gdal-bin libgdal-dev build-essential

  - name: Install Python dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest flake8 requests geopandas fiona pyproj

  - name: Lint code
    run: |
      flake8 dags tests

  - name: Run tests
    run: |
      pytest tests/

  - name: ✅ Print badge proof
    if: success()
    run: |
      echo "::notice title=Badge Unlocked::brick_e4_automation_$(date +%s)"
